LU decomposition
SpirinEgor/HSE.numerical_methods pull request #11
Opened 2020-12-17 16:54 UTC by dariadiatlova

2020-12-18 15:32 UTC, SokolovYaroslav requested changes

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +    true_L, true_U = lu(A)[1], lu(A)[2]
`_, true_L, true_U = lu(A)`
или
`true_L, true_U = lu(A)[1:3]`

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +    ans = np.isclose([true_L, true_U], [L, U], atol = 1e-8)
Есть просто `np.allclose`

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +        print('Correct')
Лучше делать `assert`-ы
То есть 
`assert np.allclose(...), f"Oops, something goes wrong"`
А еще лучше
```
from numpy.testing import assert_allclose
assert_allclose(...)
```

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +        raise ValueError("matrix should be square")
Для цели проверки чего-то есть `assert`-ы
Пример применения написал в другом месте уже

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +        print('Incorrect')
А где точка входа в программу? Ну то есть `if __name__ == "__main__"`. А то тест вижу, тестовую матрицу вижу, а где вызывается тест с тестовой матрицей не вижу

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +    return (L, U)
Скобочки излишни (это кстати Пайчарм умеет подсказывать)

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +def LU(A:np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
Две пустые строки по пепу должно быть

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +def test(LU, A:np.ndarray) -> NoReturn:
И здесь две пустые строки по пепу

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +def LU(A:np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
А еще после двоеточия должен быть пробел по пепу

2020-12-18 15:32 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +                L[i, j] = 1 / U[j, j] * (A[i, j] - L[i, :j] @ U[:j, j])
Чуть позже подумаю, как тут можно параллелизовать :)

2020-12-18 15:36 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +    L, U = np.diag(np.ones(A.shape[0])), np.zeros_like(A, dtype = np.float)
`np.diag(np.ones(A.shape[0]))` можно заменить на `np.eye(A.shape[0])`

2020-12-18 20:50 UTC, dariadiatlova commented on exam/LU_decomposition_dariadiatlova.py
> +        raise ValueError("matrix should be square")
Поправила

2020-12-18 20:54 UTC, dariadiatlova commented on exam/LU_decomposition_dariadiatlova.py
> +        print('Correct')
Тоже вроде поправила – это окей, что по-мимо коммента после f"Matrix should be square", он еще другие ошибки кидает? 
<img width="921" alt="Снимок экрана 2020-12-18 в 23 53 02" src="https://user-images.githubusercontent.com/55180898/102660491-2bbd8680-418c-11eb-82bb-2a5df2748d81.png">

2020-12-18 20:59 UTC, dariadiatlova commented on exam/LU_decomposition_dariadiatlova.py
> +        print('Incorrect')
Добавила, через main() с аргументами вызываю

2020-12-19 14:12 UTC, SokolovYaroslav commented on exam/LU_decomposition_dariadiatlova.py
> +main(A, LU, test, print_matrix)
Это лучше писать внутри `if __name__ == "__main__"`
Я могу придумать две причины:

- Современные IDE умеют сразу запускать такую конструкцию без надобности писать что-то в консоли и тп
- Когда я напишу `import %this_file%`, весь этот код начнёт выполнятся (что явно не является желательным поведением). А условие `if __name__ == "__main__"` как раз явно говорит, что код внутри этого ифа должен выполнятся только в том случае, если этот файл -- точка входа в программу

2020-12-19 14:12 UTC, SokolovYaroslav requested changes
Sample comment

2020-12-20 14:34 UTC, merged