baseline qr-algo and tests
SpirinEgor/HSE.numerical_methods pull request #19
Opened 2020-12-20 17:10 UTC by Stasiche

2020-12-20 20:00 UTC, SokolovYaroslav requested changes

2020-12-20 20:00 UTC, SokolovYaroslav commented on exam/14_QR_algo/main.py
> +        evals = np.sort(np.unique(np.diag(A_)))[::-1]
Сортить можно в самом конце

А еще в сорте есть ключ, который делает сортировку по убыванию)

2020-12-20 20:00 UTC, SokolovYaroslav commented on exam/14_QR_algo/main.py
> +# TODO stop crit
мб while not np.allclose(p_evals, evals, rtol=eps)

2020-12-20 20:37 UTC, SokolovYaroslav commented on exam/14_QR_algo/main.py
> +        evals = np.sort(np.unique(np.diag(A_)))[::-1]
Со вторым я обосрался

2020-12-20 22:56 UTC, Stasiche commented
![image](https://user-images.githubusercontent.com/26529547/102726413-b8547a00-432f-11eb-8534-d8c3c319b36c.png)
![image](https://user-images.githubusercontent.com/26529547/102726417-bb4f6a80-432f-11eb-933f-9696db7f65a7.png)

2020-12-21 02:38 UTC, SpirinEgor approved these changes

2020-12-21 02:38 UTC, merged