add algo and tests
SpirinEgor/HSE.numerical_methods pull request #3
Opened 2020-12-16 17:54 UTC by Stasiche

2020-12-17 14:45 UTC, SpirinEgor requested changes
А сложение и вычитание с другой спарс матрицей? Вроде бы Яревский и это просил

2020-12-17 14:45 UTC, SpirinEgor commented on 05.Sparse/main.py
> +    def __init__(self, values: np.ndarray, ia: np.ndarray, ja: np.ndarray):
А что `ia` и `ja` обозначают?) Индексы строк и колонок? Может как-то более понятно назвать?

2020-12-17 14:45 UTC, SpirinEgor commented on 05.Sparse/main.py
> +    def __init__(self, values: np.ndarray, ia: np.ndarray, ja: np.ndarray):
Хмм, а можешь рассказать, как ты тут всё хранишь? А то что-то я не понимаю :(

2020-12-17 14:45 UTC, SpirinEgor commented on 05.Sparse/test.py
> +print("it's fine")
Хмм, ну вообще для тестов можно было бы какой-нибудь unittest использовать, чтобы по красоте. Но это так, если время есть поразбираться)

2020-12-18 14:38 UTC, SokolovYaroslav commented on 05.Sparse/test.py
> +print("it's fine")
pytest круче

2020-12-18 16:22 UTC, Stasiche commented
> А сложение и вычитание с другой спарс матрицей? Вроде бы Яревский и это просил

я сначала пульнул, а потом он попросил) буду допиливать)

2020-12-18 16:31 UTC, Stasiche commented on 05.Sparse/main.py
> +    def __init__(self, values: np.ndarray, ia: np.ndarray, ja: np.ndarray):
он такой способ предлагает на лекции: values -- массив ненулевых элементов; ia -- по сути кумулятивная сумма количества ненулевых элементов в строках выше (то есть ia(1)=1, ia(k+1) = ia(k)+[число ненулевых элментов k-ой строки]; ja -- номера столбцов у каждого элемента из values.
В более понятных обозначениях не вижу смысла -- эти обозначения взяты с лекции, логично их и использовать, имхо, тем более они будто бы более понятны, чем в том же scipy

2020-12-20 12:35 UTC, SpirinEgor commented on 05.Sparse/main.py
> +    def __init__(self, values: np.ndarray, ia: np.ndarray, ja: np.ndarray):
Окей, можно и так.
Тогда можешь этот текст в док стрингу закинуть?

2020-12-20 13:12 UTC, SpirinEgor approved these changes

2020-12-20 13:12 UTC, merged